### PR TITLE
Adds parser for CloudFormation SNS events

### PR DESCRIPTION
**Pull request by lorengordon**
Fixes https://github.com/arabold/aws-to-slack/issues/36.

I'm happy to work tests before merging. Could use some guidance on how the new tests are working and the expected setup. For example, I see where the `generic` parser test is validating the parser return, but the `autoscaling` and `codepipeline` tests seem to be taking a different approach.

### CODE REVIEW

**Comment by homeyjd** [comment]
You're right, tests are still in their infancy.  I'd be appreciative of any feedback you can offer :).  

You're right -- `generic.test.js` and `sns.test.js` take a very different approach to testing because they're oddballs.  The `tests/parsers/_parser.js` module(which should probably be renamed to `_parser_mock.js`) is intended to be a mock-generator with some convenience functions that test (minimally): 
1) parser can be loaded
1) parser can successfully parse SNS messages
1) parser _is selected by root handler_ when that example event is received (pretty important for expected production operation!)

I'd love for `_parser.js` to enable a future contributor to:
- drop in an example event their parser should pick up
- copy/paste a couple lines of code (like `require('./parser.js').named('myParser').hereIsMyExampleObject({...})`)
- [optionally] add their own parser-specific tests after that

That's what I tried to do with [`autoscaling.test.js`](https://github.com/homeyjd/aws-to-slack/blob/master/test/parsers/autoscaling.test.js) -- you bring your own message format, and the mock handles the rest.

**Comment by homeyjd** [comment]
@nason provided an example event on base repo: https://github.com/arabold/aws-to-slack/issues/37
I added a new parser and test:
https://github.com/homeyjd/aws-to-slack/blob/master/test/parsers/codepipelineCloudWatch.test.js
Kinda hoping tests have the ability to stay this simple in the future.

**Comment by lorengordon** [comment]
That example helps a lot...

What do you think about changing the `matchesSNS` input argument from `event` to `message`, to align better with the expected value? That was part of what threw me when looking at the autoscaling test; I didn't know which part of the event data was being passed, it didn't actually _look_ like an event...

https://github.com/homeyjd/aws-to-slack/blob/accaa7c83623e2f372adfb17633bbf4526ac66a4/test/parsers/_parser_mock.js#L41

**Comment by homeyjd** [comment]
Great point, it would be way more consistent, thanks! https://github.com/homeyjd/aws-to-slack/commit/56ad1418d502f6524818ca4c9fe4504fa7532388

**Comment by lorengordon** [comment]
For the cloudformation parser (and beanstalk), we'll also need to be able to pass in the SNS `Subject` value...

Suggestion:
```diff
diff --git a/test/parsers/_parser_mock.js b/test/parsers/_parser_mock.js
index aa553a5..2b441d7 100644
--- a/test/parsers/_parser_mock.js
+++ b/test/parsers/_parser_mock.js
@@ -38,7 +38,7 @@ class ParserMock {
         * @param {string|{}} event Object or string payload
         * @returns {ParserMock} Returns self for chain-able stacks
         */
-       matchesSNS(message) {
+       matchesSNS(message, subject="TestInvoke") {
                if (typeof message !== "string") {
                        message = JSON.stringify(message);
                }
@@ -58,7 +58,7 @@ class ParserMock {
                                        "Signature": "http://example.com/signature",
                                        "SigningCertUrl": "http://example.com/signingcerturl",
                                        "UnsubscribeUrl": "http://example.com/unsubscribeurl",
-                                       "Subject": "TestInvoke",
+                                       "Subject": subject,
                                        "MessageId": `95df01b4-ee${rand(2)}-5cb9-9903-4c221d41${rand(4)}`,
                                        "Message": message,
                                        "MessageAttributes": {
```

**Comment by homeyjd** [comment]
Gosh, you're right... we use "Subject" for filtering.  Good catch.  https://github.com/homeyjd/aws-to-slack/commit/720697e01094339304c9d9ad443bed58ed9bfb65

**Comment by lorengordon** [comment]
Ok, added a couple tests. The second is failing, expectedly at the moment, since the parser is returning an empty object (as it should).

Question... the logs are quite noisy when the `message` is not JSON... do you find it useful to leak the parse-failure for every parser?

```
    console.log src/parsers/sns.js:32
      SNS message could not be JSON-parsed
```

**Comment by homeyjd** [comment]
The leaky output has been bothering me too. https://github.com/homeyjd/aws-to-slack/commit/508599144c136c63235c0af92dc11fb005659051. That work?

You're testing a negative case, which ParserMock doesn't have a convenience method for... Added! https://github.com/homeyjd/aws-to-slack/commit/b67ab33d28cb9b37f94e50e9b715a726960c8057 Your test could now look like this:
```js
require("./_parser_mock")
	.named("cloudformation")
	.willStopHandlerWithSnsEvent(ignoredSnsMessage, subject);
```

On another note, I had no idea CloudFormation sent messages that looked like INI format.  Strange how inconsistent some of AWS's tools can be...

**Comment by lorengordon** [comment]
> The leaky output has been bothering me too. 5085991. That work?

Output is much cleaner, thanks!

Updated the tests, all looks good now!

```
> jest test

 PASS  test/parsers/generic.test.js
 PASS  test/parsers/codepipeline.test.js
 PASS  test/parsers/cloudformation.test.js
 PASS  test/parsers/autoscaling.test.js
 PASS  test/parsers/sns.test.js
 PASS  test/parsers/codepipelineCloudWatch.test.js

Test Suites: 6 passed, 6 total
Tests:       36 passed, 36 total
Snapshots:   0 total
Time:        6.906s
Ran all test suites matching /test/i.
```

I think we're good, anything else?

**Comment by homeyjd** [comment]
Looks great, thank you for PR!

**Comment by lorengordon** [comment]
Thanks for letting me work it! I realize you probably could have knocked it out a lot faster yourself, with just the sample messages to work from! 😁

**Pull request merged**
